# Generated by Django 6.1.1 on 2026-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('textarea', 'Textarea'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('multicheckbox', 'Multi-checkbox'), ('number', 'Number')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='For select / multi-checkbox fields: ["Option A", "Option B"]'),
        ),
    ]
